-   repo: https://github.com/ambv/black
    rev: HEAD
    hooks:
    - id: black
      language_version: python

-   repo: local
    hooks:
    -   id: rustfmt
        name: Rust format
        entry: cargo
        language: system
        args:
        - fmt
        - --
        files: \.rs$
    -   id: elm-format
        name: Elm format
        entry: elm-format
        language: system
        args:
        - --validate
        -  --elm-version=0.19
        - fifthtry/frontend
        - --
        files: \.elm$
        pass_filenames: false
    -   id: clippy
        name: Clippy
        entry: sh scripts/clippy.sh
        language: system
        files: \.rs$
        pass_filenames: false
    -   id: tomlfmt
        name: Format TOML Files
        entry: sh scripts/toml-fmt.sh
        language: system
        files: Cargo.toml$
        pass_filenames: false

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-added-large-files
      language_version: python
      args:
      - --maxkb=500
    - id: trailing-whitespace
      language_version: python
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
      language_version: python
    - id: flake8
      language_version: python
      args:
      - --max-line-length=88
      - --ignore=E203,W503
      exclude: (.*/migrations/.*\.py)$
    - id: flake8
      language_version: python
      name: Flake8 migrations
      args:
      - --ignore=E501,W503
      - --max-line-length=88
      files: (.*/migrations/.*\.py)$
    - id: check-case-conflict
      language_version: python
    - id: check-symlinks
      language_version: python
    - id: end-of-file-fixer
      language_version: python
