[package]
name = "fbt"
version = "0.1.0"
authors = ["Sitesh <siteshpattanaik001@gmail.com>"]
edition = "2018"

[workspace]
members = ["fbt_lib"]

[dependencies]
fbt-lib = { path = "fbt_lib" }
colored = "2"
