[package]
name = "fbt"
version = "0.1.0"
authors = ["Sitesh <siteshpattanaik001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.116", features = ["derive"]}
toml = "0.5.7"
