[package]
name = "fbt"
version = "0.1.0"
authors = ["Sitesh <siteshpattanaik001@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "0"
vec1 = "1"
