[package]
name = "fbt_lib"
version = "0.1.0"
authors = ["Sitesh <siteshpattanaik001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "0"
vec1 = "1"
colored = "2"
