[package]
name = "fbt-lib"
version = "0.1.15"
authors = ["Sitesh <siteshpattanaik001@gmail.com>", "Amit Upadhyay <upadhyay@gmail.com>"]
edition = "2021"
description = "folder based testing tool (library)"
license = "BSD-2-Clause"
homepage = "https://www.fifthtry.com/fifthtry/fbt/"

[dependencies]
ftd = "0.1.16"
walkdir = "2"
rand = "0"
colored = "2"
diffy = "0.2.1"